# -*- coding: utf-8 -*-
"""GenData

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13N1O023dYm4BRcwoHFc0isugSsVffce_
"""

import csv
import random

# Define possible values for each label
age_values = [i for i in range(40, 51)]  # Age: Numeric
occupation_values = ["Business", "Job", "None"]  # Occupation
lifestyle_values = ["Sedentary", "Active"]  # Lifestyle
family_diabetic_history_values = ["Yes", "No"]  # Family Diabetic History
eating_habits_values = ["Nutritional", "Junk Food"]  # Eating Habits
pre_diabetic_condition_values = ["Yes", "No"]  # Pre Diabetic Condition

# Number of instances to create
num_instances = 50

# Create and populate dataset
dataset = []
for _ in range(num_instances):
    instance = {
        "Age": random.choice(age_values),
        "Occupation": random.choice(occupation_values),
        "Lifestyle": random.choice(lifestyle_values),
        "Family Diabetic History": random.choice(family_diabetic_history_values),
        "Eating Habits": random.choice(eating_habits_values),
        "Pre Diabetic Condition": random.choice(pre_diabetic_condition_values)
    }
    dataset.append(instance)

# Save the dataset as a CSV file
csv_file_path = "dataset.csv"
with open(csv_file_path, mode='w', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=dataset[0].keys())
    writer.writeheader()
    writer.writerows(dataset)

print(f"Dataset saved as '{csv_file_path}'.")